### ISSUE TITLE
Is the trimming after the barcode in process_10xReads necessary?

### ISSUE THREAD

**Issue by alxsimon** [ucdavis-bioinformatics/proc10xG#2]
Hi,
in process_10xReads the default for the `--trim` option is 7bp.

I was wondering why this was set up in the first place as it is not indicated in the README.
Does it change a lot to the final quality if I set it to 0? 
As 7bp feels like a lot of data being left behind.

Thanks!
Alexis

**Comment by alxsimon** [comment]
Sorry, in fact I digged a little bit in the code and realised the trimmed fragment is stored and reattached during the regen step.

But I am still interested in knowing why it needs to be trimmed, is there another barcode there?

**Comment by msettles** [comment]
Thats the random primer sequence and not actual genome sequence, its also not very complex sequence

**Comment by alxsimon** [comment]
Thanks for your answer.
